# Welcome to this final setup of jupyter notebooks
#here we try to finish this topics assignment in less than 48 hours :'(

In [1]:
import pandas as pd
import numpy as np

In [2]:
df_train = pd.read_csv("https://raw.githubusercontent.com/Akaysimmer/topics-in-BA/main/train.csv")
df_test = pd.read_csv("https://raw.githubusercontent.com/Akaysimmer/topics-in-BA/main/test.csv")

In [3]:
df_train.head()

,id,name,release_date,artists,total_tracks,t_name0,t_name1,t_name2,t_dur0,t_dur1,...,t_val0,t_val1,t_val2,t_tempo0,t_tempo1,t_tempo2,t_sig0,t_sig1,t_sig2,popularity
0,0,Ya Solo Eres Mi Ex,2021-09-09,"La Adictiva Banda San José de Mesillas,",7,Ya Solo Eres Mi Ex,La Malagueña,México Lindo y Querido,222133,189133.0,...,0.626,0.878,0.833,74.924,126.970,197.836,4.0,3.0,3.0,51
1,1,Nibiru,2019-11-29,"Ozuna,",18,Nibiru,Hasta Que Salga el Sol,Temporal,158826,188480.0,...,0.158,0.598,0.484,173.023,96.042,148.019,4.0,4.0,4.0,67
2,2,DAMN.,2017-04-14,"Kendrick Lamar,",14,BLOOD.,DNA.,YAH.,118066,185946.0,...,0.494,0.422,0.648,156.907,139.913,69.986,4.0,4.0,4.0,81
3,3,Did I Shave My Legs For This?,1996-01-01,"Deana Carter,",11,I've Loved Enough To Know,We Danced Anyway,Count Me In,203693,202533.0,...,0.755,0.651,0.263,120.285,94.054,130.011,4.0,4.0,4.0,53
4,4,glisten,2018-05-04,"Jeremy Zucker,",4,all the kids are depressed,wildfire,glisten (interlude),169973,163000.0,...,0.707,0.426,0.466,103.861,129.170,116.349,4.0,4.0,4.0,70

In [4]:
df_test.head()

,id,name,release_date,artists,total_tracks,t_name0,t_name1,t_name2,t_dur0,t_dur1,...,t_live2,t_val0,t_val1,t_val2,t_tempo0,t_tempo1,t_tempo2,t_sig0,t_sig1,t_sig2
0,160000,Vizlaxy One,2021-08-24,"The Vizlaxy,",11,Ciko,Kumne,Pod Sem,34901,33343.0,...,0.0785,0.0397,0.0381,0.0374,89.674,84.987,122.585,3.0,4.0,4.0
1,160001,OTW (Acoustic Version),2018-06-25,"Missy & Blonde,",1,OTW - Acoustic Version,NaN,NaN,201655,NaN,...,NaN,0.5300,NaN,NaN,129.998,NaN,NaN,4.0,NaN,NaN
2,160002,Ocean Avenue,2003-01-01,"Yellowcard,",13,Way Away,Breathing,Ocean Avenue,202093,218706.0,...,0.0947,0.3640,0.5700,0.7860,179.644,179.581,173.734,4.0,4.0,4.0
3,160003,Bloomsday (Remastered),2018-02-16,"Esbe,",19,Float - Remastered,Fulfill / The Dream - Remastered,Wanderlust - Remastered,182783,416000.0,...,0.2600,0.4560,0.1070,0.5830,194.107,89.533,134.016,3.0,4.0,4.0
4,160004,Miss You,2021-09-03,"SLANDER, Ganja White Night,",1,Miss You,NaN,NaN,200000,NaN,...,NaN,0.0526,NaN,NaN,74.473,NaN,NaN,4.0,NaN,NaN

In [5]:
df_train.shape

(160000, 45)

In [6]:
# Separating the Target variable from the training set
Y = df_train['popularity']
df_train.drop(['popularity'], axis=1, inplace=True)
print(df_train.shape, Y.shape)

(160000, 44) (160000,)

In [7]:
# Concatenating the df_train and df_test into one Dataframe
df = pd.concat([df_train, df_test], axis=0)
df.shape

(181207, 44)

In [8]:
# Setting the ID as index
df = df.set_index('id')

# Summarizing the Dataset 
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 181207 entries, 0 to 181206
Data columns (total 43 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   name          181206 non-null  object
 1   release_date  181207 non-null  object
 2   artists       181207 non-null  object
 3   total_tracks  181207 non-null  int64
 4   t_name0       181206 non-null  object
 5   t_name1       127203 non-null  object
 6   t_name2       122884 non-null  object
 7   t_dur0        181207 non-null  int64
 8   t_dur1        127203 non-null  float64
 9   t_dur2        122884 non-null  float64
 10  t_dance0      180957 non-null  float64
 11  t_dance1      127064 non-null  float64
 12  t_dance2      122801 non-null  float64
 13  t_energy0     180957 non-null  float64
 14  t_energy1     127064 non-null  float64
 15  t_energy2     122801 non-null  float64
 16  t_key0        180957 non-null  float64
 17  t_key1        127064 non-null  float64
 18  t_key2        122801 non-null  float64
 19  t_mode0       180957 non-null  float64
 20  t_mode1       127064 non-null  float64
 21  t_mode2       122801 non-null  float64
 22  t_speech0     180957 non-null  float64
 23  t_speech1     127064 non-null  float64
 24  t_speech2     122801 non-null  float64
 25  t_acous0      180957 non-null  float64
 26  t_acous1      127064 non-null  float64
 27  t_acous2      122801 non-null  float64
 28  t_ins0        180957 non-null  float64
 29  t_ins1        127064 non-null  float64
 30  t_ins2        122801 non-null  float64
 31  t_live0       180957 non-null  float64
 32  t_live1       127064 non-null  float64
 33  t_live2       122801 non-null  float64
 34  t_val0        180957 non-null  float64
 35  t_val1        127064 non-null  float64
 36  t_val2        122801 non-null  float64
 37  t_tempo0      180957 non-null  float64
 38  t_tempo1      127064 non-null  float64
 39  t_tempo2      122801 non-null  float64
 40  t_sig0        180957 non-null  float64
 41  t_sig1        127064 non-null  float64
 42  t_sig2        122801 non-null  float64
dtypes: float64(35), int64(2), object(6)
memory usage: 60.8+ MB

In [16]:
# Describing the Dataset
df.describe()

,total_tracks,t_dur0,t_dur1,t_dur2,t_dance0,t_dance1,t_dance2,t_energy0,t_energy1,t_energy2,...,t_live2,t_val0,t_val1,t_val2,t_tempo0,t_tempo1,t_tempo2,t_sig0,t_sig1,t_sig2
count,181207.000000,1.812070e+05,1.272030e+05,1.228840e+05,180957.000000,127064.000000,122801.000000,180957.000000,127064.000000,122801.000000,...,122801.000000,180957.000000,127064.000000,122801.000000,180957.000000,127064.000000,122801.000000,180957.000000,127064.000000,122801.000000
mean,11.021175,1.990648e+05,2.134121e+05,2.142064e+05,0.606277,0.608402,0.609340,0.605146,0.628930,0.616476,...,0.190217,0.468309,0.492792,0.484944,119.739825,121.092684,120.653097,3.896323,3.910148,3.902436
std,23.121934,1.152684e+05,1.095481e+05,9.786787e+04,0.184047,0.177483,0.179398,0.236689,0.232757,0.230984,...,0.154766,0.255980,0.250204,0.253048,31.201646,30.476803,30.920109,0.510765,0.434635,0.464349
min,1.000000,1.485000e+03,4.120000e+03,2.113000e+03,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,1.507690e+05,1.688800e+05,1.693190e+05,0.490000,0.498750,0.500000,0.458000,0.489000,0.477000,...,0.098200,0.261000,0.298000,0.289000,95.514000,96.624000,96.005000,4.000000,4.000000,4.000000
50%,10.000000,1.920620e+05,2.037300e+05,2.064130e+05,0.630000,0.631000,0.627000,0.633000,0.660000,0.647000,...,0.127000,0.460000,0.498000,0.482000,119.987000,120.019000,119.988000,4.000000,4.000000,4.000000
75%,14.000000,2.336000e+05,2.427920e+05,2.448750e+05,0.745000,0.736000,0.742000,0.793000,0.811000,0.792000,...,0.237000,0.669000,0.689000,0.682000,140.016000,141.138000,141.026000,4.000000,4.000000,4.000000
max,1190.000000,1.082819e+07,7.054236e+06,6.145123e+06,0.988000,0.992000,0.985000,1.000000,1.000000,1.000000,...,0.996000,1.000000,1.000000,1.000000,239.713000,248.500000,246.322000,5.000000,5.000000,5.000000

# Data cleaning
#now we shall clean the data

In [18]:
# Dropping all the non-numerical columns
numdf = df.drop(columns = ['name', 'release_date', 'artists', 't_name0', 't_name1', 't_name2'], inplace = True, axis = 1)

KeyError: "['name' 'release_date' 'artists' 't_name0' 't_name1' 't_name2'] not found in axis"